### PR TITLE
Fix error if $transactionCode is null

### PR DESCRIPTION
**Pull request by woutersamaey**

### CODE REVIEW

**Comment by wimverstuyf** [comment]
Thanks for the PR! But this doesn't seem to be the correct change:

The TransactionParser allows for the transactioncode to be empty so this would make it a correct change. (Though making this change would mean the getTransactionCode() would also have to be able to return a null value.)

But: The transactioncode can only be empty if no line of type "TransactionPart1" is available. According to the spec this line is mandatory so the transactioncode can only be empty when the CODA-file is malformed.
A better solution would be to throw an exception in the TransactionParser when $transactionCode is empty. Agree?

See file https://www.febelfin.be/sites/default/files/2019-04/standard-coda-2.6-nl.pdf
Page 6: "2 = beweging. deel 1 is steeds aanwezig, delen 2 en 3 komen voor wanneer nodig."

**Comment by wimverstuyf** [comment]
Sorry for the late response.
Could you provide an example CODA-file which produces this error? Then I'll take a look at it.

**Comment by woutersamaey** [comment]
@wimverstuyf can I email you the file? I'm not keen on sharing CODA files on Github :)

**Comment by wimverstuyf** [comment]
sure, you can send it to info [at] eenvoudigfactureren.be

**Comment by wimverstuyf** [comment]
PR no longer applicable

**Pull request closed without merging**
